
# NUMPY

In [8]:
import numpy as np

In [9]:
a=np.array([1,3,4,6])
b=np.array([2,3,7,8])
c=a*b
print(c)

[ 2  9 28 48]


In [10]:
d=a/b
print(d)

[0.5        1.         0.57142857 0.75      ]


In [11]:
e=a**b
print(e)

[      1      27   16384 1679616]


In [12]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr2=arr1.reshape((4,2))
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]





#Vertically Stacking Vectors

In [20]:
v1=np.array([1,2,3])
v2=np.array([7,8,9])

np.vstack((v1,v2,v2,v2,v1))

array([[1, 2, 3],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [1, 2, 3]])

#HORIZONTAL STACKING VECTORS

In [34]:
h1=np.array([1,2,3])
h2=np.array([7,8,9])
h3=np.zeros((3))
h4=np.ones((4))

print('h1 = ',h1)
print('h2 = ',h2)
print('h3 = ',h3)
print('h4 = ',h4)
np.hstack((h1,h2,h3,h4))

h1 =  [1 2 3]
h2 =  [7 8 9]
h3 =  [0. 0. 0.]
h4 =  [1. 1. 1. 1.]


array([1., 2., 3., 7., 8., 9., 0., 0., 0., 1., 1., 1., 1.])

# MISCULLANEOUS

OPEN DATA FROM FILE

In [16]:
import numpy as np
filedata=np.genfromtxt('datapractice.txt',delimiter=',')
filedata=filedata.astype('int')
print(filedata)
filedata1=filedata.astype('float')
print(filedata1)
#file=file.astype('int32')
#print(file)

[[  24    2   45  457]
 [3467  234  123   45]
 [  44   47   87   52]
 [ 415  447  878   44]]
[[2.400e+01 2.000e+00 4.500e+01 4.570e+02]
 [3.467e+03 2.340e+02 1.230e+02 4.500e+01]
 [4.400e+01 4.700e+01 8.700e+01 5.200e+01]
 [4.150e+02 4.470e+02 8.780e+02 4.400e+01]]


In [17]:
filedata>50

array([[False, False, False,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True, False]])

In [22]:
((filedata>50) & (filedata<100))

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [23]:
filedata[filedata>50]

array([ 457, 3467,  234,  123,   87,   52,  415,  447,  878])

In [27]:
np.any(filedata>100,axis=1)

array([ True,  True, False,  True])

In [28]:
print(filedata)

[[  24    2   45  457]
 [3467  234  123   45]
 [  44   47   87   52]
 [ 415  447  878   44]]


In [30]:
print(filedata[1:4,0:2])

[[3467  234]
 [  44   47]
 [ 415  447]]


ACCESS 3467,44,45,52 FROM THE DATA

In [31]:
print(filedata[1:3,(0,3)])

[[3467   45]
 [  44   52]]


GET INDEX VALUES (0,0),(2,1),(0,2),(3,3)

In [33]:
print(filedata[(0,2,0,3),(0,1,2,3)])

[24 47 45 44]
